### ISSUE TITLE
Implement flow for managing existing auto-imports

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#104]
![image](https://user-images.githubusercontent.com/57259/182466306-e6c3d250-95a9-4d68-b178-cb04e60c3f31.png)

**Comment by german-mergestat** [comment]
Hey @patrickdevivo some questions here:

1. ![trash](https://user-images.githubusercontent.com/109089565/188680004-c992e77f-d94d-4991-bf8e-6fe848ff1f1e.png) Trash button will be implemented? or Should I simply not show this up?

2. Records that are "importing" should be shown? I mean, if a record has `last_import` in `null`, this record will be showed with an _**on loading**_ ![Spinner](https://user-images.githubusercontent.com/109089565/188679469-48f099ba-6156-4ba5-857e-6b0c434b99ec.png) icon?

**Comment by patrickdevivo** [comment]
> 1. ![trash](https://user-images.githubusercontent.com/109089565/188680004-c992e77f-d94d-4991-bf8e-6fe848ff1f1e.png) Trash button will be implemented? or Should I simply not show this up?

Yes, let's implement the trash icon for now - the functionality will have to wait until we have the GraphQL mutation in place (to do the removal) but let's have the button there.


> 3. Records that are "importing" should be shown? I mean, if a record has `last_import` in `null`, this record will be showed with an _**on loading**_ ![Spinner](https://user-images.githubusercontent.com/109089565/188679469-48f099ba-6156-4ba5-857e-6b0c434b99ec.png) icon?

Yes - I like that. Instead of `loading` icon though, can we show a clock icon? Since it's more that it's waiting for the first import to run
