### ISSUE TITLE
Add `labels` column to `github_issues` and `github_pull_requests`

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#136]
A `JSONB` `labels` column for `github_issues` and `github_pull_requests` would be pretty useful. We should be able to access this and implement in our schema.

**Comment by patrickdevivo** [comment]
Sure - so in `mergestat/mergestat` in the `github_repo_issues` and `github_repo_prs` tables we are not currently syncing the `labels` columns:

https://github.com/mergestat/mergestat/blob/main/extensions/internal/github/repo_issues.go#L274 and https://github.com/mergestat/mergestat/blob/main/extensions/internal/github/repo_prs.go#L354

we have had a user request to include these in our data tables: `github_issues` and `github_pull_requests`.

So to address this, we should:

- [ ] Create a migration to add these two columns to the table (as `jsonb` type? @amenowanna )
- [ ] Update the syncers for these two tables to populate those columns

**Comment by ramiroJCB** [comment]
Makes sense , thank you Patrick
