### ISSUE TITLE
Investigate faster local dev flows when working on the `worker`

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#142]
Right now the dev-loop cycle working on the `worker` is really slow. Compile time is slow and there's not really a "sanctioned" path on how to do local development and testing.

**Comment by patrickdevivo** [comment]
Maybe if we switch to dynamically linking `libgit2` vs statically?

**Comment by amenowanna** [comment]
When we pick this ticket up let's not spend more than 1 day on it.

**Comment by amenowanna** [comment]
When you guys get a chance to check this out. I keep getting consistent results when I dirty the cache and run the build again. Could be you guys already have buildkit enabled but it would appear I don’t.
docker-compose build worker
  => [builder 9/9] RUN PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/share/pkgconfig/libgit2/lib/pkgconfig/ make                                                                                                   53.9s
vs
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build worker
 => [builder 9/9] RUN PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/share/pkgconfig/libgit2/lib/pkgconfig/ make                                                                                                   37.1s

**Comment by patrickdevivo** [comment]
Another area to look would be cutting down the number of unnecessary files copied into the Docker container when building the worker:

```
➜  fuse git:(main) ✗ du -hs ui
959M	ui
````

That's almost a gig in the `ui` directory (mostly `node_modules`):

```
➜  ui git:(main) ✗ du -hs node_modules
957M	node_modules
```

There's no need for all that to be copied over in `COPY . .` when building the worker, I bet doing so could speed things up a bit as well
