### ISSUE TITLE
Add consistent starting and finished log messages for all syncs

### ISSUE THREAD

**Issue by amenowanna** [mergestat/fuse#161]
Not all syncs have a "starting" and "finished" log entry. We should update the log messages to be consistent so we can analyze the logs. The content of the message should be the same and the only difference should be the action of "starting" or "finished".

We should use the name of the sync type or the new short name in the log message so it is clear what sync we are referencing.

"starting Git Commits sync"
"finished Git Commits sync"

Current view of the logs

![Image](https://user-images.githubusercontent.com/10135546/186963384-21324f84-f515-47d3-9ed6-df0b1f915c87.png)

**Comment by patrickdevivo** [comment]
we should also include some context about the repo, maybe just the repo URL so we have that context in the log as well

**Comment by ramiroJCB** [comment]
so "starting Git Commits sync for repoUrl" seems good

**Comment by amenowanna** [comment]
I like that!
