### ISSUE TITLE
Implement a better logging pattern in fuse/worker

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/fuse#180]

**Comment by patrickdevivo** [comment]
@ramiroJCB could you please expand on this one? Do you recall which type of logging you were thinking of when you added this? Logging to standard out from our services or logging to the DB during syncs?

**Comment by ramiroJCB** [comment]
@patrickdevivo  we may close this ,  essentially because  is  duplicate for this  https://github.com/mergestat/fuse/issues/232
