### ISSUE TITLE
Implement UI for "empty" repos page

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#193]
When there are no repos added or imported yet, the `/repos` page should look like:

![Image](https://user-images.githubusercontent.com/57259/189147521-7ecfe903-edbc-4b16-8578-183eeb82b069.png)

When there are no repos added or imported yet **and** there's no GitHub PAT in the DB, show a special UI (need to regroup on which one we want to show - see examples in Figma)

**Comment by german-mergestat** [comment]
This logic already is implemented 🙂.
