### ISSUE TITLE
Add linter rules for all types of files in fuse

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/fuse#199]
- [x] Use our execeptions (SQLFLUFF excluded rules & UI Linting rules)
- [x] exclude Generated File
- [x] Now that this is a workflow  , we can share fure initial template  and share it to other repos as workflow

**Comment by amenowanna** [comment]
My suggestion would be to explore [GitHub Super Linter](https://github.com/github/super-linter). Also, I have started to use sqlfluff in [fuse-examples](https://github.com/mergestat/fuse-examples) so I have some personal preferences for what rules I exclude from that linter. Should we maybe look at centralizing our linting rules so we can use the same ones across different repos?

**Comment by patrickdevivo** [comment]
love it! my only suggestion would be to coordinate with @german-mergestat since he added a JS/TS linter in the UI - ideally we don't double lint and can incorporate his lint setup into the "super linter"

**Comment by ramiroJCB** [comment]
In regards  to  the sqlfluff and the linter in the UI here is an example on exceptions  in the github super linter https://github.com/github/super-linter/blob/main/docs/using-rules-files.md
