### ISSUE TITLE
Start using the sync type `short_name` column in the UI

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#223]
Anywhere we list a sync type and it's description, we should use the `short_name` returned by the API now, since we track that in the DB.

**Comment by german-mergestat** [comment]
> 

I think It is missing replace names in Bread crumb.

**Comment by patrickdevivo** [comment]
Also in this "popover":

![Image](https://user-images.githubusercontent.com/57259/193357489-6b317e2f-1262-4971-ba6d-f5a180b6d7f1.png)
