### ISSUE TITLE
Repo auto imports UI sometimes is "out of sync"

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#248]
Repo auto imports UI sometimes is "out of sync" - for example when a new repo auto import is added, there's a moment where the table is "stale" and then eventually it catches up when the poll kicks in. Maybe we need to trigger a refetch in more places?

Also - should we consider a loading state here if there isn't one already?

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/57259/189935409-0fc1072c-f235-4881-8a86-7a7f8425a1ef.png">

**Comment by german-mergestat** [comment]
I recall this issue was resolved.. I will pass this issue to review just to check and if it is well then close it.

**Comment by patrickdevivo** [comment]
Could not reproduce it - thanks for the heads up (and for the fix!). Closing
