### ISSUE TITLE
Create index for all public tables and their foreign constraints

### ISSUE THREAD

**Issue by ramiroJCB** [mergestat/fuse#302]

**Comment by amenowanna** [comment]
Changes made as part of this [commit](https://github.com/mergestat/fuse/commit/c9b171d76fd41e11448b76f8a291fd735817750a)

**Comment by patrickdevivo** [comment]
@amenowanna I validated this a bit in our latest deployments, seems fine. I'll let you close out, but lgtm

**Comment by amenowanna** [comment]
Indexing definitely helped!
