### ISSUE TITLE
Deleting an `auto_import` should also delete the repos it imported

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#311]
We can do this by adding a `CASCADE` to the `repo_import_id` foreign key constraint on the `repos` table, similar to what was done for the data tables pointing back to `repos`.

This will enable #309 (it will be important to have that warning in the UI)

**Comment by ramiroJCB** [comment]
Should we tackle this ticket faster ? I should be able to do in a few minutes @patrickdevivo

**Comment by patrickdevivo** [comment]
yep - go for it
