### ISSUE TITLE
Implement GraphQL query to retrieve current user

### ISSUE THREAD

**Issue by patrickdevivo** [mergestat/fuse#320]
Now that we have some user context in the UI, we need to be able to fetch the current DB user and display it in the UI. Probably need to add a custom function for retrieving the current DB user.

<img width="402" alt="image" src="https://user-images.githubusercontent.com/57259/192059413-fcab1466-87c9-42bd-b1c1-1a84b32cf29d.png">

**Comment by amenowanna** [comment]
Should be as simple as `select user;`
